name: Mypy
# run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y python3-pip
      - run: pip install -e .
      - run: pip install mypy
      - run: mypy org_rw
