name: Testing
# run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y python3-pip
      - run: pip install -e .
      - run: pip install pytest
      - run: pytest

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y python3-pip
      - run: pip install -e .
      - run: pip install mypy
      - run: mypy org_rw

  stability-extra-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: apt-get update && apt-get install -y git-core python3-pip
    - run: pip install -e .
    - run: bash extra-tests/check_all.sh
